using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace TurnBasedBattle.Editor
{
    public static class SpellParticlePrefabGenerator
    {
        private const string OutputFolder = "Assets/MyStuff/Prefab/GeneratedSpellParticles";
        private const string DefaultMaterialPath = "Assets/MyStuff/MaterialForParticle/Test.mat";
        private const string TrailMaterialPath = "Assets/MyStuff/MaterialForParticle/Trail.mat";
        private const string BarrierMaterialPath = "Assets/MyStuff/MaterialForParticle/Barrier.mat";
        private const string AutoGenerateSessionKey = "TurnBattle.GeneratedSpellParticles.AutoGenerated";

        private static Material defaultMaterial;
        private static Material trailMaterial;
        private static Material barrierMaterial;

        [InitializeOnLoadMethod]
        private static void AutoGenerateIfMissing()
        {
            if (SessionState.GetBool(AutoGenerateSessionKey, false))
            {
                return;
            }

            SessionState.SetBool(AutoGenerateSessionKey, true);
            EditorApplication.delayCall += () =>
            {
                if (!AssetDatabase.IsValidFolder(OutputFolder) || !System.IO.File.Exists($"{OutputFolder}/薪火の魔法.prefab"))
                {
                    GenerateAll();
                }
            };
        }

        [MenuItem("TurnBattle/Generate Spell Particle Prefabs")]
        public static void GenerateAll()
        {
            EnsureFolder();
            LoadMaterials();

            Create薪火();
            Create破戒();
            Create火護();
            Create聖印();
            Create氷礫();
            Create斬風();
            Create旋風();
            Create黒耀();
            Create吸熱();
            Create氷狼();
            Create火継();
            Create氷剣();
            Create火葬();
            Create焼毀();
            Create星火();
            Create泉();

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log($"Generated spell particle prefabs in {OutputFolder}");
        }

        private static void Create薪火()
        {
            GameObject root = CreateRoot("薪火の魔法", 3.2f);
            AddFlameColumn(root.transform, "HPFuelFlame", new Color(1f, 0.32f, 0.05f, 1f), 70, 2.8f, 1.8f);
            AddAura(root.transform, "AttackBuffEmbers", new Color(1f, 0.74f, 0.22f, 1f), 34, 1.2f);
            AddSparks(root.transform, "BloodCostSparks", new Color(0.9f, 0.04f, 0.02f, 1f), 24, 2.6f);
            Save(root, "薪火の魔法.prefab");
        }

        private static void Create破戒()
        {
            GameObject root = CreateRoot("破戒の魔法", 3.5f);
            AddShockwave(root.transform, "CrackShockwave", new Color(0.16f, 0.03f, 0.2f, 1f), 2.2f, 0.9f);
            AddBurst(root.transform, "BrokenVowFragments", new Color(0.55f, 0.08f, 0.8f, 1f), 58, 3.0f, 0.18f, 1.0f);
            AddDarkSmoke(root.transform, "LowHpMiasma", new Color(0.05f, 0.02f, 0.06f, 0.72f), 36, 2.2f);
            Save(root, "破戒の魔法.prefab");
        }

        private static void Create火護()
        {
            GameObject root = CreateRoot("火護の魔法", 3.4f);
            AddAura(root.transform, "WarmGuardRing", new Color(1f, 0.42f, 0.08f, 1f), 56, 1.7f);
            AddFlameColumn(root.transform, "SoftFireVeil", new Color(1f, 0.58f, 0.16f, 1f), 38, 2.4f, 1.2f);
            AddRisingMotifs(root.transform, "SmallHealLights", new Color(1f, 0.92f, 0.48f, 1f), 32, 1.4f);
            Save(root, "火護の魔法.prefab");
        }

        private static void Create聖印()
        {
            GameObject root = CreateRoot("聖印の魔法", 4.1f);
            AddLightPillar(root.transform, "HolyPillar", new Color(1f, 0.96f, 0.72f, 1f), 78, 3.2f);
            AddAura(root.transform, "SacredSealRing", new Color(0.65f, 0.95f, 1f, 1f), 64, 2.0f);
            AddRisingMotifs(root.transform, "LargeHealMotes", new Color(0.75f, 1f, 0.92f, 1f), 46, 2.2f);
            Save(root, "聖印の魔法.prefab");
        }

        private static void Create氷礫()
        {
            GameObject root = CreateRoot("氷礫の魔法", 3.0f);
            AddDirectionalShardBurst(root.transform, "IcePebbles", new Color(0.55f, 0.9f, 1f, 1f), 46, 3.8f, 0.16f);
            AddColdMist(root.transform, "FrostMist", new Color(0.68f, 0.94f, 1f, 0.6f), 24, 1.2f);
            Save(root, "氷礫の魔法.prefab");
        }

        private static void Create斬風()
        {
            GameObject root = CreateRoot("斬風の魔法", 3.0f);
            AddWindSlash(root.transform, "FirstSlashArc", new Color(0.62f, 1f, 0.72f, 1f), 38, 4.2f, 0.2f);
            AddSparks(root.transform, "CutAirFlecks", new Color(0.9f, 1f, 0.9f, 1f), 18, 2.0f);
            Save(root, "斬風の魔法.prefab");
        }

        private static void Create旋風()
        {
            GameObject root = CreateRoot("旋風の魔法", 4.2f);
            AddVortex(root.transform, "MultiHitVortex", new Color(0.48f, 1f, 0.82f, 1f), 95, 2.8f, 2.1f);
            AddWindSlash(root.transform, "RepeatedCutStreaks", new Color(0.9f, 1f, 0.95f, 1f), 54, 5.0f, 0.12f);
            Save(root, "旋風の魔法.prefab");
        }

        private static void Create黒耀()
        {
            GameObject root = CreateRoot("黒耀の魔法", 3.6f);
            AddStoneBurst(root.transform, "ObsidianPlates", new Color(0.03f, 0.025f, 0.035f, 1f), 44, 2.2f);
            AddAura(root.transform, "BlackGuardRing", new Color(0.1f, 0.08f, 0.12f, 1f), 48, 1.9f);
            AddDust(root.transform, "EarthDust", new Color(0.28f, 0.22f, 0.16f, 0.6f), 36, 1.1f);
            Save(root, "黒耀の魔法.prefab");
        }

        private static void Create吸熱()
        {
            GameObject root = CreateRoot("吸熱の魔法", 3.5f);
            AddInwardSparks(root.transform, "HeatDrainInflow", new Color(1f, 0.26f, 0.06f, 1f), 72, 2.2f);
            AddAura(root.transform, "AttackHeatAura", new Color(1f, 0.48f, 0.1f, 1f), 45, 1.5f);
            Save(root, "吸熱の魔法.prefab");
        }

        private static void Create氷狼()
        {
            GameObject root = CreateRoot("氷狼の魔法", 3.8f);
            AddDirectionalShardBurst(root.transform, "WolfFangIce", new Color(0.45f, 0.86f, 1f, 1f), 64, 4.6f, 0.22f);
            AddColdMist(root.transform, "WolfBreathMist", new Color(0.55f, 0.85f, 1f, 0.68f), 44, 1.7f);
            AddShockwave(root.transform, "HowlRing", new Color(0.75f, 0.95f, 1f, 0.8f), 1.7f, 0.35f);
            Save(root, "氷狼の魔法.prefab");
        }

        private static void Create火継()
        {
            GameObject root = CreateRoot("火継の魔法", 3.4f);
            AddFlameColumn(root.transform, "InheritedFlame", new Color(1f, 0.38f, 0.05f, 1f), 56, 2.5f, 1.5f);
            AddAura(root.transform, "PassingTorchBuff", new Color(1f, 0.77f, 0.2f, 1f), 40, 1.6f);
            Save(root, "火継の魔法.prefab");
        }

        private static void Create氷剣()
        {
            GameObject root = CreateRoot("氷剣の魔法", 3.4f);
            AddDirectionalShardBurst(root.transform, "IceBladeThrust", new Color(0.58f, 0.94f, 1f, 1f), 36, 5.2f, 0.28f);
            AddWindSlash(root.transform, "FrozenCutLine", new Color(0.82f, 1f, 1f, 1f), 22, 4.2f, 0.16f);
            AddColdMist(root.transform, "BladeFrost", new Color(0.62f, 0.88f, 1f, 0.5f), 28, 1.1f);
            Save(root, "氷剣の魔法.prefab");
        }

        private static void Create火葬()
        {
            GameObject root = CreateRoot("火葬の魔法", 4.2f);
            AddExplosion(root.transform, "CremationBlast", new Color(1f, 0.22f, 0.02f, 1f), 105, 3.8f, 0.45f);
            AddFlameColumn(root.transform, "AfterburnColumn", new Color(1f, 0.5f, 0.05f, 1f), 68, 3.2f, 2.0f);
            AddDarkSmoke(root.transform, "AshSmoke", new Color(0.18f, 0.13f, 0.1f, 0.75f), 48, 2.5f);
            Save(root, "火葬の魔法.prefab");
        }

        private static void Create焼毀()
        {
            GameObject root = CreateRoot("焼毀の魔法", 4.5f);
            AddExplosion(root.transform, "ScorchingRuinBlast", new Color(1f, 0.12f, 0.01f, 1f), 130, 4.4f, 0.55f);
            AddSparks(root.transform, "RuinCinders", new Color(1f, 0.75f, 0.18f, 1f), 82, 4.0f);
            AddDarkSmoke(root.transform, "BurntRuinSmoke", new Color(0.08f, 0.06f, 0.055f, 0.82f), 56, 2.8f);
            Save(root, "焼毀の魔法.prefab");
        }

        private static void Create星火()
        {
            GameObject root = CreateRoot("星火の魔法", 5.0f);
            AddLightPillar(root.transform, "StarJudgementCore", new Color(1f, 0.98f, 0.8f, 1f), 100, 4.0f);
            AddExplosion(root.transform, "MutualAnnihilationFlash", new Color(1f, 0.55f, 0.08f, 1f), 160, 5.0f, 0.75f);
            AddShockwave(root.transform, "FinalStarRing", new Color(1f, 0.86f, 0.36f, 1f), 3.4f, 1.4f);
            Save(root, "星火の魔法.prefab");
        }

        private static void Create泉()
        {
            GameObject root = CreateRoot("泉の魔法", 4.0f);
            AddWaterFountain(root.transform, "CleansingSpring", new Color(0.3f, 0.78f, 1f, 1f), 76, 2.4f);
            AddAura(root.transform, "PurifyRipple", new Color(0.5f, 1f, 0.9f, 1f), 52, 1.8f);
            AddRisingMotifs(root.transform, "RecoveryDroplets", new Color(0.72f, 1f, 0.95f, 1f), 34, 1.8f);
            Save(root, "泉の魔法.prefab");
        }

        private static GameObject CreateRoot(string name, float duration)
        {
            GameObject root = new GameObject(name);
            ParticleSystem ps = root.AddComponent<ParticleSystem>();
            root.AddComponent<OneShotParticleCallback>();

            ParticleSystem.MainModule main = ps.main;
            main.duration = duration;
            main.loop = false;
            main.playOnAwake = false;
            main.startLifetime = 0.15f;
            main.startSpeed = 0f;
            main.startSize = 0.01f;
            main.startColor = new Color(1f, 1f, 1f, 0f);
            main.simulationSpace = ParticleSystemSimulationSpace.World;
            main.stopAction = ParticleSystemStopAction.Callback;

            ParticleSystem.EmissionModule emission = ps.emission;
            emission.enabled = false;

            return root;
        }

        private static ParticleSystem AddSystem(Transform parent, string name)
        {
            GameObject child = new GameObject(name);
            child.transform.SetParent(parent, false);
            ParticleSystem ps = child.AddComponent<ParticleSystem>();
            ParticleSystem.MainModule main = ps.main;
            main.loop = false;
            main.playOnAwake = false;
            main.simulationSpace = ParticleSystemSimulationSpace.World;
            main.stopAction = ParticleSystemStopAction.None;
            ApplyRenderer(ps, defaultMaterial, 100);
            return ps;
        }

        private static void AddFlameColumn(Transform parent, string name, Color color, short burstCount, float duration, float height)
        {
            ParticleSystem ps = AddSystem(parent, name);
            ParticleSystem.MainModule main = ps.main;
            main.duration = duration;
            main.startLifetime = new ParticleSystem.MinMaxCurve(0.55f, 1.05f);
            main.startSpeed = new ParticleSystem.MinMaxCurve(0.8f, 1.8f);
            main.startSize = new ParticleSystem.MinMaxCurve(0.16f, 0.42f);
            main.startColor = new ParticleSystem.MinMaxGradient(color, WithAlpha(Color.yellow, 0.65f));
            main.gravityModifier = -0.08f;

            ParticleSystem.EmissionModule emission = ps.emission;
            emission.SetBursts(new[] { new ParticleSystem.Burst(0f, burstCount), new ParticleSystem.Burst(0.45f, (short)(burstCount / 2)) });

            ParticleSystem.ShapeModule shape = ps.shape;
            shape.enabled = true;
            shape.shapeType = ParticleSystemShapeType.Cone;
            shape.angle = 18f;
            shape.radius = 0.35f;
            shape.position = new Vector3(0f, -height * 0.25f, 0f);

            ParticleSystem.ColorOverLifetimeModule col = ps.colorOverLifetime;
            col.enabled = true;
            col.color = GradientAlpha(color, 0.95f, 0f);

            ParticleSystem.SizeOverLifetimeModule size = ps.sizeOverLifetime;
            size.enabled = true;
            size.size = new ParticleSystem.MinMaxCurve(1f, AnimationCurve.EaseInOut(0f, 0.5f, 1f, 0.05f));
        }

        private static void AddAura(Transform parent, string name, Color color, short count, float radius)
        {
            ParticleSystem ps = AddSystem(parent, name);
            ParticleSystem.MainModule main = ps.main;
            main.duration = 3.2f;
            main.startLifetime = new ParticleSystem.MinMaxCurve(1.4f, 2.2f);
            main.startSpeed = new ParticleSystem.MinMaxCurve(0.05f, 0.25f);
            main.startSize = new ParticleSystem.MinMaxCurve(0.08f, 0.2f);
            main.startColor = new ParticleSystem.MinMaxGradient(color, WithAlpha(Color.white, 0.55f));

            ParticleSystem.EmissionModule emission = ps.emission;
            emission.SetBursts(new[] { new ParticleSystem.Burst(0f, count), new ParticleSystem.Burst(1.0f, (short)(count / 2)) });

            ParticleSystem.ShapeModule shape = ps.shape;
            shape.enabled = true;
            shape.shapeType = ParticleSystemShapeType.Donut;
            shape.radius = radius;
            shape.donutRadius = 0.08f;

            ParticleSystem.VelocityOverLifetimeModule velocity = ps.velocityOverLifetime;
            velocity.enabled = true;
            velocity.orbitalZ = new ParticleSystem.MinMaxCurve(-0.8f, 0.8f);

            ApplyRenderer(ps, barrierMaterial != null ? barrierMaterial : defaultMaterial, 101);
        }

        private static void AddSparks(Transform parent, string name, Color color, short count, float speed)
        {
            ParticleSystem ps = AddSystem(parent, name);
            ParticleSystem.MainModule main = ps.main;
            main.duration = 3.0f;
            main.startLifetime = new ParticleSystem.MinMaxCurve(0.5f, 1.2f);
            main.startSpeed = new ParticleSystem.MinMaxCurve(speed * 0.45f, speed);
            main.startSize = new ParticleSystem.MinMaxCurve(0.035f, 0.1f);
            main.startColor = new ParticleSystem.MinMaxGradient(color, WithAlpha(Color.yellow, 0.85f));

            ParticleSystem.EmissionModule emission = ps.emission;
            emission.SetBursts(new[] { new ParticleSystem.Burst(0f, count), new ParticleSystem.Burst(0.6f, (short)(count / 2)) });

            ParticleSystem.ShapeModule shape = ps.shape;
            shape.enabled = true;
            shape.shapeType = ParticleSystemShapeType.Sphere;
            shape.radius = 0.2f;

            ParticleSystemRenderer renderer = ps.GetComponent<ParticleSystemRenderer>();
            renderer.renderMode = ParticleSystemRenderMode.Stretch;
            renderer.lengthScale = 2.3f;
            renderer.velocityScale = 0.8f;
            ApplyRenderer(ps, trailMaterial != null ? trailMaterial : defaultMaterial, 102);
        }

        private static void AddBurst(Transform parent, string name, Color color, short count, float speed, float minSize, float maxSize)
        {
            ParticleSystem ps = AddSystem(parent, name);
            ParticleSystem.MainModule main = ps.main;
            main.duration = 3.0f;
            main.startLifetime = new ParticleSystem.MinMaxCurve(0.7f, 1.7f);
            main.startSpeed = new ParticleSystem.MinMaxCurve(speed * 0.4f, speed);
            main.startSize = new ParticleSystem.MinMaxCurve(minSize, maxSize);
            main.startColor = new ParticleSystem.MinMaxGradient(color, WithAlpha(Color.white, 0.55f));

            ParticleSystem.EmissionModule emission = ps.emission;
            emission.SetBursts(new[] { new ParticleSystem.Burst(0f, count) });

            ParticleSystem.ShapeModule shape = ps.shape;
            shape.enabled = true;
            shape.shapeType = ParticleSystemShapeType.Sphere;
            shape.radius = 0.1f;
        }

        private static void AddExplosion(Transform parent, string name, Color color, short count, float speed, float size)
        {
            AddBurst(parent, name, color, count, speed, size * 0.45f, size);
            AddShockwave(parent, name + "Ring", WithAlpha(color, 0.8f), 2.4f, 0.55f);
        }

        private static void AddShockwave(Transform parent, string name, Color color, float radius, float size)
        {
            ParticleSystem ps = AddSystem(parent, name);
            ParticleSystem.MainModule main = ps.main;
            main.duration = 2.2f;
            main.startLifetime = new ParticleSystem.MinMaxCurve(0.7f, 1.2f);
            main.startSpeed = new ParticleSystem.MinMaxCurve(1.0f, 2.2f);
            main.startSize = new ParticleSystem.MinMaxCurve(size, size * 1.4f);
            main.startColor = color;

            ParticleSystem.EmissionModule emission = ps.emission;
            emission.SetBursts(new[] { new ParticleSystem.Burst(0f, (short)36) });

            ParticleSystem.ShapeModule shape = ps.shape;
            shape.enabled = true;
            shape.shapeType = ParticleSystemShapeType.Donut;
            shape.radius = radius;
            shape.donutRadius = 0.02f;

            ApplyRenderer(ps, barrierMaterial != null ? barrierMaterial : defaultMaterial, 99);
        }

        private static void AddDarkSmoke(Transform parent, string name, Color color, short count, float radius)
        {
            ParticleSystem ps = AddSystem(parent, name);
            ParticleSystem.MainModule main = ps.main;
            main.duration = 4f;
            main.startLifetime = new ParticleSystem.MinMaxCurve(1.6f, 3.2f);
            main.startSpeed = new ParticleSystem.MinMaxCurve(0.12f, 0.55f);
            main.startSize = new ParticleSystem.MinMaxCurve(0.35f, 0.9f);
            main.startColor = color;
            main.gravityModifier = -0.05f;

            ParticleSystem.EmissionModule emission = ps.emission;
            emission.SetBursts(new[] { new ParticleSystem.Burst(0f, count), new ParticleSystem.Burst(1f, (short)(count / 2)) });

            ParticleSystem.ShapeModule shape = ps.shape;
            shape.enabled = true;
            shape.shapeType = ParticleSystemShapeType.Sphere;
            shape.radius = radius;
        }

        private static void AddColdMist(Transform parent, string name, Color color, short count, float radius)
        {
            AddDarkSmoke(parent, name, color, count, radius);
        }

        private static void AddDust(Transform parent, string name, Color color, short count, float radius)
        {
            AddDarkSmoke(parent, name, color, count, radius);
        }

        private static void AddDirectionalShardBurst(Transform parent, string name, Color color, short count, float speed, float size)
        {
            ParticleSystem ps = AddSystem(parent, name);
            ParticleSystem.MainModule main = ps.main;
            main.duration = 3.0f;
            main.startLifetime = new ParticleSystem.MinMaxCurve(0.65f, 1.4f);
            main.startSpeed = new ParticleSystem.MinMaxCurve(speed * 0.65f, speed);
            main.startSize = new ParticleSystem.MinMaxCurve(size * 0.45f, size);
            main.startColor = new ParticleSystem.MinMaxGradient(color, WithAlpha(Color.white, 0.9f));
            main.startRotation = new ParticleSystem.MinMaxCurve(-1.4f, 1.4f);
            main.gravityModifier = 0.04f;

            ParticleSystem.EmissionModule emission = ps.emission;
            emission.SetBursts(new[] { new ParticleSystem.Burst(0f, count) });

            ParticleSystem.ShapeModule shape = ps.shape;
            shape.enabled = true;
            shape.shapeType = ParticleSystemShapeType.Cone;
            shape.angle = 12f;
            shape.radius = 0.18f;

            ParticleSystemRenderer renderer = ps.GetComponent<ParticleSystemRenderer>();
            renderer.renderMode = ParticleSystemRenderMode.Stretch;
            renderer.lengthScale = 1.8f;
            renderer.velocityScale = 0.9f;
            ApplyRenderer(ps, trailMaterial != null ? trailMaterial : defaultMaterial, 102);
        }

        private static void AddWindSlash(Transform parent, string name, Color color, short count, float speed, float size)
        {
            ParticleSystem ps = AddSystem(parent, name);
            ParticleSystem.MainModule main = ps.main;
            main.duration = 3.0f;
            main.startLifetime = new ParticleSystem.MinMaxCurve(0.35f, 0.85f);
            main.startSpeed = new ParticleSystem.MinMaxCurve(speed * 0.55f, speed);
            main.startSize = new ParticleSystem.MinMaxCurve(size * 0.4f, size);
            main.startColor = new ParticleSystem.MinMaxGradient(color, WithAlpha(Color.white, 0.7f));

            ParticleSystem.EmissionModule emission = ps.emission;
            emission.SetBursts(new[] { new ParticleSystem.Burst(0f, count), new ParticleSystem.Burst(0.35f, (short)(count / 2)) });

            ParticleSystem.ShapeModule shape = ps.shape;
            shape.enabled = true;
            shape.shapeType = ParticleSystemShapeType.Circle;
            shape.radius = 1.15f;
            shape.arc = 135f;

            ParticleSystemRenderer renderer = ps.GetComponent<ParticleSystemRenderer>();
            renderer.renderMode = ParticleSystemRenderMode.Stretch;
            renderer.lengthScale = 3.2f;
            renderer.velocityScale = 1.1f;
            ApplyRenderer(ps, trailMaterial != null ? trailMaterial : defaultMaterial, 102);
        }

        private static void AddVortex(Transform parent, string name, Color color, short count, float radius, float speed)
        {
            ParticleSystem ps = AddSystem(parent, name);
            ParticleSystem.MainModule main = ps.main;
            main.duration = 4.0f;
            main.startLifetime = new ParticleSystem.MinMaxCurve(0.8f, 1.7f);
            main.startSpeed = new ParticleSystem.MinMaxCurve(0.35f, speed);
            main.startSize = new ParticleSystem.MinMaxCurve(0.06f, 0.18f);
            main.startColor = new ParticleSystem.MinMaxGradient(color, WithAlpha(Color.white, 0.85f));

            ParticleSystem.EmissionModule emission = ps.emission;
            emission.SetBursts(new[] { new ParticleSystem.Burst(0f, count), new ParticleSystem.Burst(1.1f, (short)(count / 2)) });

            ParticleSystem.ShapeModule shape = ps.shape;
            shape.enabled = true;
            shape.shapeType = ParticleSystemShapeType.Donut;
            shape.radius = radius;
            shape.donutRadius = 0.1f;

            ParticleSystem.VelocityOverLifetimeModule velocity = ps.velocityOverLifetime;
            velocity.enabled = true;
            velocity.orbitalZ = new ParticleSystem.MinMaxCurve(2.0f, 4.2f);
            velocity.radial = new ParticleSystem.MinMaxCurve(-0.2f, 0.2f);

            ApplyRenderer(ps, trailMaterial != null ? trailMaterial : defaultMaterial, 101);
        }

        private static void AddStoneBurst(Transform parent, string name, Color color, short count, float speed)
        {
            ParticleSystem ps = AddSystem(parent, name);
            ParticleSystem.MainModule main = ps.main;
            main.duration = 3.2f;
            main.startLifetime = new ParticleSystem.MinMaxCurve(1.1f, 2.2f);
            main.startSpeed = new ParticleSystem.MinMaxCurve(0.5f, speed);
            main.startSize = new ParticleSystem.MinMaxCurve(0.18f, 0.44f);
            main.startColor = new ParticleSystem.MinMaxGradient(color, WithAlpha(new Color(0.22f, 0.18f, 0.24f), 1f));
            main.gravityModifier = 0.25f;
            main.startRotation = new ParticleSystem.MinMaxCurve(-3.14f, 3.14f);

            ParticleSystem.EmissionModule emission = ps.emission;
            emission.SetBursts(new[] { new ParticleSystem.Burst(0f, count) });

            ParticleSystem.ShapeModule shape = ps.shape;
            shape.enabled = true;
            shape.shapeType = ParticleSystemShapeType.Sphere;
            shape.radius = 0.45f;
        }

        private static void AddInwardSparks(Transform parent, string name, Color color, short count, float radius)
        {
            ParticleSystem ps = AddSystem(parent, name);
            ParticleSystem.MainModule main = ps.main;
            main.duration = 3.2f;
            main.startLifetime = new ParticleSystem.MinMaxCurve(0.7f, 1.5f);
            main.startSpeed = new ParticleSystem.MinMaxCurve(-2.8f, -1.1f);
            main.startSize = new ParticleSystem.MinMaxCurve(0.05f, 0.15f);
            main.startColor = new ParticleSystem.MinMaxGradient(color, WithAlpha(Color.yellow, 0.85f));

            ParticleSystem.EmissionModule emission = ps.emission;
            emission.SetBursts(new[] { new ParticleSystem.Burst(0f, count), new ParticleSystem.Burst(0.8f, (short)(count / 2)) });

            ParticleSystem.ShapeModule shape = ps.shape;
            shape.enabled = true;
            shape.shapeType = ParticleSystemShapeType.Sphere;
            shape.radius = radius;

            ApplyRenderer(ps, trailMaterial != null ? trailMaterial : defaultMaterial, 102);
        }

        private static void AddRisingMotifs(Transform parent, string name, Color color, short count, float radius)
        {
            ParticleSystem ps = AddSystem(parent, name);
            ParticleSystem.MainModule main = ps.main;
            main.duration = 4f;
            main.startLifetime = new ParticleSystem.MinMaxCurve(1.0f, 2.2f);
            main.startSpeed = new ParticleSystem.MinMaxCurve(0.35f, 0.95f);
            main.startSize = new ParticleSystem.MinMaxCurve(0.08f, 0.22f);
            main.startColor = new ParticleSystem.MinMaxGradient(color, WithAlpha(Color.white, 0.8f));
            main.gravityModifier = -0.12f;

            ParticleSystem.EmissionModule emission = ps.emission;
            emission.SetBursts(new[] { new ParticleSystem.Burst(0f, count), new ParticleSystem.Burst(1.0f, (short)(count / 2)) });

            ParticleSystem.ShapeModule shape = ps.shape;
            shape.enabled = true;
            shape.shapeType = ParticleSystemShapeType.Circle;
            shape.radius = radius;
        }

        private static void AddLightPillar(Transform parent, string name, Color color, short count, float height)
        {
            ParticleSystem ps = AddSystem(parent, name);
            ParticleSystem.MainModule main = ps.main;
            main.duration = 4f;
            main.startLifetime = new ParticleSystem.MinMaxCurve(1.1f, 2.6f);
            main.startSpeed = new ParticleSystem.MinMaxCurve(0.2f, 0.85f);
            main.startSize = new ParticleSystem.MinMaxCurve(0.14f, 0.42f);
            main.startColor = new ParticleSystem.MinMaxGradient(color, WithAlpha(Color.white, 0.95f));
            main.gravityModifier = -0.08f;

            ParticleSystem.EmissionModule emission = ps.emission;
            emission.SetBursts(new[] { new ParticleSystem.Burst(0f, count), new ParticleSystem.Burst(1.2f, (short)(count / 2)) });

            ParticleSystem.ShapeModule shape = ps.shape;
            shape.enabled = true;
            shape.shapeType = ParticleSystemShapeType.Cone;
            shape.angle = 8f;
            shape.radius = 0.7f;
            shape.position = new Vector3(0f, -height * 0.35f, 0f);

            ApplyRenderer(ps, barrierMaterial != null ? barrierMaterial : defaultMaterial, 101);
        }

        private static void AddWaterFountain(Transform parent, string name, Color color, short count, float height)
        {
            ParticleSystem ps = AddSystem(parent, name);
            ParticleSystem.MainModule main = ps.main;
            main.duration = 4f;
            main.startLifetime = new ParticleSystem.MinMaxCurve(1.0f, 2.0f);
            main.startSpeed = new ParticleSystem.MinMaxCurve(0.7f, 1.8f);
            main.startSize = new ParticleSystem.MinMaxCurve(0.08f, 0.22f);
            main.startColor = new ParticleSystem.MinMaxGradient(color, WithAlpha(Color.white, 0.8f));
            main.gravityModifier = 0.18f;

            ParticleSystem.EmissionModule emission = ps.emission;
            emission.SetBursts(new[] { new ParticleSystem.Burst(0f, count), new ParticleSystem.Burst(1.1f, (short)(count / 2)) });

            ParticleSystem.ShapeModule shape = ps.shape;
            shape.enabled = true;
            shape.shapeType = ParticleSystemShapeType.Cone;
            shape.angle = 22f;
            shape.radius = 0.28f;
            shape.position = new Vector3(0f, -height * 0.2f, 0f);
        }

        private static void ApplyRenderer(ParticleSystem ps, Material material, int sortingOrder)
        {
            ParticleSystemRenderer renderer = ps.GetComponent<ParticleSystemRenderer>();
            renderer.material = material != null ? material : defaultMaterial;
            renderer.sortingLayerName = "Effect";
            renderer.sortingOrder = sortingOrder;
        }

        private static ParticleSystem.MinMaxGradient GradientAlpha(Color color, float startAlpha, float endAlpha)
        {
            Gradient gradient = new Gradient();
            gradient.SetKeys(
                new[]
                {
                    new GradientColorKey(color, 0f),
                    new GradientColorKey(color, 1f),
                },
                new[]
                {
                    new GradientAlphaKey(startAlpha, 0f),
                    new GradientAlphaKey(endAlpha, 1f),
                });
            return new ParticleSystem.MinMaxGradient(gradient);
        }

        private static Color WithAlpha(Color color, float alpha)
        {
            color.a = alpha;
            return color;
        }

        private static void Save(GameObject root, string fileName)
        {
            string path = $"{OutputFolder}/{fileName}";
            PrefabUtility.SaveAsPrefabAsset(root, path);
            Object.DestroyImmediate(root);
        }

        private static void EnsureFolder()
        {
            EnsureFolder("Assets/MyStuff/Prefab");
            EnsureFolder(OutputFolder);
        }

        private static void EnsureFolder(string path)
        {
            if (AssetDatabase.IsValidFolder(path))
            {
                return;
            }

            string parent = System.IO.Path.GetDirectoryName(path)?.Replace("\\", "/");
            string folder = System.IO.Path.GetFileName(path);
            if (!string.IsNullOrEmpty(parent) && !AssetDatabase.IsValidFolder(parent))
            {
                EnsureFolder(parent);
            }

            AssetDatabase.CreateFolder(parent, folder);
        }

        private static void LoadMaterials()
        {
            defaultMaterial = AssetDatabase.LoadAssetAtPath<Material>(DefaultMaterialPath);
            trailMaterial = AssetDatabase.LoadAssetAtPath<Material>(TrailMaterialPath);
            barrierMaterial = AssetDatabase.LoadAssetAtPath<Material>(BarrierMaterialPath);

            if (defaultMaterial == null)
            {
                defaultMaterial = AssetDatabase.GetBuiltinExtraResource<Material>("Default-Particle.mat");
            }
        }
    }
}
